### ISSUE TITLE
Creative tab icon shows missing texture

### ISSUE THREAD

**Issue by brisingraerowing** [jaquadro/StorageDrawersExtras#1]
As per title.

The only supported mod I have is Forestry. I don't use Biomes O' Plenty or Natura.

**Comment by jaquadro** [comment]
Oh, I bet it's because it's specifically tied to Natura (they've got fixed places in the ID space).  Thanks.

**Comment by LukewarmYeti** [comment]
Yes this is also happening with only Biomes installed. Furthermore, when looking at any of the drawers with the one probe or Waila, you get a broken texture, which is probably due to the same issue.

Edit: you get the missing texture effect when you break the drawers as well

**Comment by jaquadro** [comment]
The tab texture should be fixed.
