### ISSUE TITLE
[1.12.2] Storage Drawers Extras 1.12-3.1.0 works, but is not marked as such on Curse

### ISSUE THREAD

**Issue by sandalle** [jaquadro/StorageDrawersExtras#12]
[Storage Drawers Extras 1.12-3.1.0](https://minecraft.curseforge.com/projects/storage-drawers-extras/files/2443623) works on MC 1.12.2 (Forge Mod Loader 14.23.0.2515), but is not marked as such on Curse disallowing modpacks from using it.

**Comment by jaquadro** [comment]
Thanks, this is now fixed on curse.

**Comment by sandalle** [comment]
Thank you @jaquadro . :)
