### ISSUE TITLE
[1.12 Crash]

### ISSUE THREAD

**Issue by TheXWolf** [jaquadro/StorageDrawersExtras#5]
Crash during load for 1.12 newest Forge, Chameleon 1.12-4.0 and SD 1.12-501.
[https://pastebin.com/zPyRS1K5](url)

**Comment by jaquadro** [comment]
... did Forge just kill my access to add recipes through the vanilla CraftingManager?

**Comment by jaquadro** [comment]
Fixed in 5.0.2, but recipes are fully disabled until Forge gets a little further.

**Comment by TheXWolf** [comment]
It's funny, because I read the log and was thinking, I can't be reading that right. But oh well GG forge.
