### ISSUE TITLE
1.12-3.0.1 crashes dedicated server Forge 1.12 build 2382

### ISSUE THREAD

**Issue by kreezxil** [jaquadro/StorageDrawersExtras#7]
Notes:
     on startup

crash report:
https://gist.github.com/2b529c04bcd332f80db7975de483a17e

fml server latest:
https://gist.github.com/e5f026bb69101f7e2feb105dace5bc3d

**Comment by jaquadro** [comment]
oyea I still gotta update this for new forge stuff

**Comment by Kris1432** [comment]
I was just about to poke you to do this @jaquadro haha, didn't know if you had forgotten to do this mod since you already updated StorageDrawers.

**Comment by jaquadro** [comment]
Should be fixed in 3.1.0
